/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TroViet.Views.NguoiDung;

import TroViet.Controllers.ChuyenManHinhNguoiDung;
import TroViet.Controllers.DanhMuc;
import TroViet.DAO.UserRole;
import TroViet.Utils.SessionManager;
import TroViet.Views.Login.TrangChuChung;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author WINDOWS
 */
public class Main_NguoiDung extends javax.swing.JFrame {

    String user = SessionManager.getSession().getUser().getRole().getName();
    public Main_NguoiDung() {
        initComponents();
        setLocationRelativeTo(null);
        
        ChuyenManHinhNguoiDung control = new ChuyenManHinhNguoiDung(jpnView);
        try {
            control.setView(jMenuTrangChu);
        } catch (SQLException ex) {
            Logger.getLogger(Main_NguoiDung.class.getName()).log(Level.SEVERE, null, ex);
        }
        List<DanhMuc> listItem = new ArrayList<>();
        listItem.add(new DanhMuc("TrangChu", jMenuTrangChu));
        listItem.add(new DanhMuc("DanhGia", jMenuDanhGia));
        System.out.println("user123" + user);
        if(user == "tenants") {
        listItem.add(new DanhMuc("HopDong", jMenuHopDong));
        listItem.add(new DanhMuc("HoaDon", jMenuHoaDon));
        }

        listItem.add(new DanhMuc("ThongTinCaNhan", jMenuThongTin));
        listItem.add(new DanhMuc("LichSuHoatDong", jMenuLichSuHD));
        control.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnView = new javax.swing.JPanel();
        lblNull = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTrangChu = new javax.swing.JMenu();
        jMenuDanhGia = new javax.swing.JMenu();
        jMenuHopDong = new javax.swing.JMenu();
        jMenuHoaDon = new javax.swing.JMenu();
        jMenuAbout = new javax.swing.JMenu();
        jMenuNguoiDung = new javax.swing.JMenu();
        jMenuThongTin = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuLichSuHD = new javax.swing.JMenu();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        btnThoat = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        btnDangXuat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jpnView.setBackground(new java.awt.Color(40, 46, 62));
        jpnView.setPreferredSize(new java.awt.Dimension(1100, 630));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNull)
                .addContainerGap(1094, Short.MAX_VALUE))
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNull)
                .addContainerGap(624, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(46, 56, 86));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 205, 31), 2));
        jMenuBar1.setForeground(new java.awt.Color(40, 46, 62));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(615, 70));

        jMenuTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        jMenuTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/home (1).png"))); // NOI18N
        jMenuTrangChu.setText("Trang chủ");
        jMenuTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuBar1.add(jMenuTrangChu);

        jMenuDanhGia.setForeground(new java.awt.Color(255, 255, 255));
        jMenuDanhGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/circle-star.png"))); // NOI18N
        jMenuDanhGia.setText("Đánh giá");
        jMenuDanhGia.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuBar1.add(jMenuDanhGia);

        jMenuHopDong.setForeground(new java.awt.Color(255, 255, 255));
        jMenuHopDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/rent (1).png"))); // NOI18N
        jMenuHopDong.setText("Hợp đồng");
        jMenuHopDong.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuBar1.add(jMenuHopDong);

        jMenuHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        jMenuHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/bill (1).png"))); // NOI18N
        jMenuHoaDon.setText("Hóa đơn");
        jMenuHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuBar1.add(jMenuHoaDon);

        jMenuAbout.setForeground(new java.awt.Color(255, 255, 255));
        jMenuAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/info (1).png"))); // NOI18N
        jMenuAbout.setText("About");
        jMenuAbout.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenuNguoiDung.setForeground(new java.awt.Color(40, 46, 62));
        jMenuNguoiDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/user (1).png"))); // NOI18N
        jMenuNguoiDung.setText("Người dùng");
        jMenuNguoiDung.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuThongTin.setForeground(new java.awt.Color(40, 46, 62));
        jMenuThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/user (1).png"))); // NOI18N
        jMenuThongTin.setText("Thông tin cá nhân");
        jMenuThongTin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuNguoiDung.add(jMenuThongTin);
        jMenuNguoiDung.add(jSeparator5);

        jMenuLichSuHD.setForeground(new java.awt.Color(40, 46, 62));
        jMenuLichSuHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/history.png"))); // NOI18N
        jMenuLichSuHD.setText("Lịch sử hoạt động");
        jMenuLichSuHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuNguoiDung.add(jMenuLichSuHD);

        jMenuAbout.add(jMenuNguoiDung);
        jMenuAbout.add(jSeparator4);

        btnThoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(40, 46, 62));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/logout (1).png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jMenuAbout.add(btnThoat);
        jMenuAbout.add(jSeparator6);

        btnDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(40, 46, 62));
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/return.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jMenuAbout.add(btnDangXuat);

        jMenuBar1.add(jMenuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn muốn đóng ứng dụng?", "Thoát?", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn muốn đăng xuất?", "Đăng xuất?", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            this.dispose();
            TrangChuChung tc;
            try {
                tc = new TrangChuChung();
                tc.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Main_NguoiDung.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDangXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_NguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_NguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_NguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_NguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_NguoiDung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnDangXuat;
    private javax.swing.JMenuItem btnThoat;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDanhGia;
    private javax.swing.JMenu jMenuHoaDon;
    private javax.swing.JMenu jMenuHopDong;
    private javax.swing.JMenu jMenuLichSuHD;
    private javax.swing.JMenu jMenuNguoiDung;
    private javax.swing.JMenu jMenuThongTin;
    private javax.swing.JMenu jMenuTrangChu;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPanel jpnView;
    private javax.swing.JLabel lblNull;
    // End of variables declaration//GEN-END:variables
}
