/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TroViet.Views.ChuTro;

import TroViet.Controllers.ChuyenManHinhChuTro;
import TroViet.Controllers.DanhMuc;
import TroViet.DAO.PhongTroEnum;
import TroViet.DAO.PhongTroDAO;
import TroViet.DAO.SessionDAO;
import TroViet.Model.PhongTro;
import TroViet.Model.SessionEntity;
import TroViet.Model.UserEntity;
import TroViet.Utils.SessionManager;
import static TroViet.Utils.SessionManager.setSession;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.YES_OPTION;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WINDOWS
 */
public class PhongTroPanel extends javax.swing.JPanel {

    /**
     * Creates new form PhongTroPanel
     */
    
    DefaultTableModel model;
    PhongTroDAO Dao = new PhongTroDAO();
    private List<PhongTro> phongtroo = new ArrayList<PhongTro>();
    DefaultTableModel tableModel = new DefaultTableModel();
    UserEntity userSS = SessionManager.getSession().getUser();
    static SessionDAO sessionDao = new SessionDAO();
    public static String idPhong, idNguoiDung;
    public static float giaPhong;
    
    
    public PhongTroPanel() {
        initComponents();
        initTable();
        LoadDataTable();
        
    }
   
    public void initTable() {
        model = (DefaultTableModel) tblPhongTro.getModel();
        String[] columns = {"ID", "ID LP", "ID ND", "ID KV", "Tên phòng", "Diện tích", "Giá phòng", "Địa chỉ", "Mô tả", "Trạng thái"};
        model.setColumnIdentifiers(columns);

        statusComboBox1.addItem("Tất cả");
        statusComboBox1.addItem(PhongTroEnum.Not_Yet.getName());
        statusComboBox1.addItem(PhongTroEnum.Rented.getName());
        statusComboBox1.addItem(PhongTroEnum.Waiting.getName());

        LoadDataTable();

        statusComboBox1.addActionListener(e -> {
            String selectedStatus = (String) statusComboBox1.getSelectedItem();
            System.out.println(selectedStatus);
            LoadDataTable(selectedStatus);
        });
    }

    public void LoadDataTable(String selectedStatus) {
        model = (DefaultTableModel) tblPhongTro.getModel();
        model.setRowCount(0);
        try {
            List<PhongTro> list = Dao.loadPhongTroData(selectedStatus);
            for (PhongTro pt : list) {
                Object[] row = {
                    pt.getId(),
                    pt.getIdMaloaiphong(),
                    pt.getIdNguoidung(),
                    pt.getIdKhuvuc(),
                    pt.getTenphong(),
                    pt.getDientich(),
                    pt.getGiaphong(),
                    pt.getDiachi(),
                    pt.getMota(),
                    pt.getStatus()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, "Lỗi truy vấn dữ liệu");
        }
    }

    public void LoadDataTable() {
        model = (DefaultTableModel) tblPhongTro.getModel();
        model.setRowCount(0);
        try {
            List<PhongTro> list = Dao.getAll();
            for (PhongTro pt : list) {
                Object[] row = {
                    pt.getId(),
                    pt.getIdMaloaiphong(),
                    pt.getIdNguoidung(),
                    pt.getIdKhuvuc(),
                    pt.getTenphong(),
                    pt.getDientich(),
                    pt.getGiaphong(),
                    pt.getDiachi(),
                    pt.getMota(),
                    pt.getStatus()
                    };
                model.addRow(row);
                }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, "Lỗi truy vấn dữ liệu");
        }
    }
    
    public long getSelectedIds() {
        long selectedRow = tblPhongTro.getSelectedRow();
        if (selectedRow < 0) {
            return -1;
        }
        long id = (long) tblPhongTro.getValueAt((int) selectedRow, 0);
        return id;
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGTinhTrang = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaLoaiPhong = new javax.swing.JTextField();
        txtMaKhuVuc = new javax.swing.JTextField();
        txtMaNguoiDung = new javax.swing.JTextField();
        txtTenPhong = new javax.swing.JTextField();
        txtDienTich = new javax.swing.JTextField();
        txtGiaPhong = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        rbDaThue = new javax.swing.JRadioButton();
        rbChuaThue = new javax.swing.JRadioButton();
        rbChoDuyet = new javax.swing.JRadioButton();
        lblId = new javax.swing.JLabel();
        btnTaoHopDong = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThungRac = new javax.swing.JButton();
        btnRest = new javax.swing.JButton();
        statusComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPhongTro = new javax.swing.JTable();

        setBackground(new java.awt.Color(40, 46, 62));

        jPanel1.setBackground(new java.awt.Color(46, 56, 86));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 205, 31), 2), "Tìm kiếm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 205, 31))); // NOI18N

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTimKiem.setForeground(new java.awt.Color(40, 46, 62));
        txtTimKiem.setText("Nhập mã phòng trọ để tìm kiếm phòng!");
        txtTimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusLost(evt);
            }
        });

        btnTimKiem.setBackground(new java.awt.Color(255, 205, 31));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(40, 46, 62));
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/magnifier.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(btnTimKiem)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(207, 243, 243));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 46, 62));
        jLabel1.setText("QUẢN LÝ PHÒNG TRỌ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(40, 46, 62));
        jLabel2.setText("Mã loại phòng:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(40, 46, 62));
        jLabel3.setText("Mã khu vực:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(40, 46, 62));
        jLabel4.setText("Mã người dùng:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(40, 46, 62));
        jLabel5.setText("Tên phòng:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(40, 46, 62));
        jLabel6.setText("Giá phòng:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(40, 46, 62));
        jLabel7.setText("Diện tích:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(40, 46, 62));
        jLabel8.setText("Địa chỉ:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(40, 46, 62));
        jLabel9.setText("Mô tả:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(40, 46, 62));
        jLabel10.setText("Tình trạng:");

        txtMaLoaiPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaLoaiPhong.setForeground(new java.awt.Color(40, 46, 62));

        txtMaKhuVuc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaKhuVuc.setForeground(new java.awt.Color(40, 46, 62));

        txtMaNguoiDung.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaNguoiDung.setForeground(new java.awt.Color(40, 46, 62));

        txtTenPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenPhong.setForeground(new java.awt.Color(40, 46, 62));

        txtDienTich.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDienTich.setForeground(new java.awt.Color(40, 46, 62));

        txtGiaPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGiaPhong.setForeground(new java.awt.Color(40, 46, 62));

        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDiaChi.setForeground(new java.awt.Color(40, 46, 62));

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane1.setViewportView(txtMoTa);

        rbDaThue.setBackground(new java.awt.Color(207, 243, 243));
        btnGTinhTrang.add(rbDaThue);
        rbDaThue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbDaThue.setForeground(new java.awt.Color(40, 46, 62));
        rbDaThue.setText("Đã thuê");

        rbChuaThue.setBackground(new java.awt.Color(207, 243, 243));
        btnGTinhTrang.add(rbChuaThue);
        rbChuaThue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbChuaThue.setForeground(new java.awt.Color(40, 46, 62));
        rbChuaThue.setText("Chưa thuê");

        rbChoDuyet.setBackground(new java.awt.Color(207, 243, 243));
        btnGTinhTrang.add(rbChoDuyet);
        rbChoDuyet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbChoDuyet.setForeground(new java.awt.Color(40, 46, 62));
        rbChoDuyet.setText("Chờ duyệt");

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblId.setForeground(new java.awt.Color(40, 46, 62));
        lblId.setText("ID");

        btnTaoHopDong.setBackground(new java.awt.Color(255, 205, 31));
        btnTaoHopDong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTaoHopDong.setForeground(new java.awt.Color(40, 46, 62));
        btnTaoHopDong.setText("Tạo hợp đồng");
        btnTaoHopDong.setEnabled(false);
        btnTaoHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoHopDongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiaChi)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rbDaThue)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbChuaThue)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbChoDuyet)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnTaoHopDong)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMaNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(24, 24, 24)
                                        .addComponent(txtMaLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(59, 59, 59)
                                        .addComponent(txtDienTich, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaKhuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblId))))
                .addGap(58, 58, 58))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaKhuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDienTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtGiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbDaThue)
                        .addComponent(rbChuaThue)
                        .addComponent(rbChoDuyet)
                        .addComponent(btnTaoHopDong)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(46, 56, 86));

        btnThem.setBackground(new java.awt.Color(255, 205, 31));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(40, 46, 62));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 205, 31));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(40, 46, 62));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 205, 31));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(40, 46, 62));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/litter.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThungRac.setBackground(new java.awt.Color(255, 205, 31));
        btnThungRac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThungRac.setForeground(new java.awt.Color(40, 46, 62));
        btnThungRac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/delete.png"))); // NOI18N
        btnThungRac.setText("Thùng rác");
        btnThungRac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThungRacActionPerformed(evt);
            }
        });

        btnRest.setBackground(new java.awt.Color(255, 205, 31));
        btnRest.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRest.setForeground(new java.awt.Color(40, 46, 62));
        btnRest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/return.png"))); // NOI18N
        btnRest.setText("Reset");
        btnRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestActionPerformed(evt);
            }
        });

        statusComboBox1.setBackground(new java.awt.Color(255, 205, 31));
        statusComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        statusComboBox1.setForeground(new java.awt.Color(40, 46, 62));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnRest, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThungRac, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(statusComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThungRac, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRest, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(statusComboBox1))
                .addContainerGap())
        );

        tblPhongTro.setBackground(new java.awt.Color(207, 243, 243));
        tblPhongTro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblPhongTro.setForeground(new java.awt.Color(40, 46, 62));
        tblPhongTro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPhongTro.setGridColor(new java.awt.Color(255, 255, 255));
        tblPhongTro.setSelectionBackground(new java.awt.Color(40, 46, 62));
        tblPhongTro.setSelectionForeground(new java.awt.Color(255, 205, 31));
        tblPhongTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhongTroMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPhongTro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        try {                                           
            // TODO add your handling code here:
            model.setRowCount(0);
            
            String keyword = txtTimKiem.getText();
            try {
                phongtroo = Dao.searchByKey(keyword);
            } catch (SQLException ex) {
                Logger.getLogger(PhongTroPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            for (PhongTro pt : phongtroo) {
                Object[] row = {
                    pt.getId(),
                    pt.getIdMaloaiphong(),
                    pt.getIdNguoidung(),
                    pt.getIdKhuvuc(),
                    pt.getTenphong(),
                    pt.getDientich(),
                    pt.getGiaphong(),
                    pt.getDiachi(),
                    pt.getMota(),
                    pt.getStatus()
                };
                model.addRow(row);
            }
            SessionEntity ss = new SessionEntity();
            ss.setUser(userSS);
            ss.setMessage("Tìm kiếm phòng trọ");
            ss.setStartTime(new Timestamp(System.currentTimeMillis()));
            sessionDao.save(ss);
            SessionEntity sss = sessionDao.getLast(userSS.getId());
            setSession(sss);
        } catch (SQLException ex) {
            Logger.getLogger(PhongTroPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        PhongTroDAO dao = new PhongTroDAO();
        PhongTro pt = new PhongTro();
        int question = JOptionPane.showConfirmDialog(this, "Thêm phòng trọ mới?", "Thêm?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (question == JOptionPane.YES_NO_OPTION) {
            try {
                pt.setIdNguoidung(Integer.parseInt(txtMaNguoiDung.getText().trim()));
                pt.setIdKhuvuc(Integer.parseInt(txtMaKhuVuc.getText().trim()));
                pt.setIdMaloaiphong(Integer.parseInt(txtMaLoaiPhong.getText().trim()));
                pt.setTenphong(txtTenPhong.getText().trim());
                pt.setDientich(Double.valueOf(txtDienTich.getText().trim()));
                pt.setGiaphong(Double.valueOf(txtGiaPhong.getText().trim()));
                pt.setDiachi(txtDiaChi.getText().trim());
                pt.setMota(txtMoTa.getText().trim());
                if (rbDaThue.isSelected()) {
                    pt.setStatus(PhongTroEnum.Rented);
                } else if (rbChuaThue.isSelected()) {
                    pt.setStatus(PhongTroEnum.Not_Yet);
                } else if (rbChoDuyet.isSelected()) {
                    pt.setStatus(PhongTroEnum.Waiting);
                }
                dao.save(pt);
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                LoadDataTable();
                SessionEntity ss = new SessionEntity();
                ss.setUser(userSS);
                ss.setMessage("Thêm phòng trọ mới");
                ss.setStartTime(new Timestamp(System.currentTimeMillis()));
                sessionDao.save(ss);
                SessionEntity sss = sessionDao.getLast(userSS.getId());
                setSession(sss);
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        PhongTroDAO dao = new PhongTroDAO();
        PhongTro pt = new PhongTro();
        int question = JOptionPane.showConfirmDialog(this, "Cập nhật", "Cập nhật?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (question == JOptionPane.YES_NO_OPTION) {
            try {
                pt.setId(Integer.parseInt(lblId.getText().trim()));
                pt.setIdNguoidung(Integer.parseInt(txtMaNguoiDung.getText().trim()));
                pt.setIdKhuvuc(Integer.parseInt(txtMaKhuVuc.getText().trim()));
                pt.setIdMaloaiphong(Integer.parseInt(txtMaLoaiPhong.getText().trim()));
                pt.setTenphong(txtTenPhong.getText().trim());
                pt.setDientich(Double.valueOf(txtDienTich.getText().trim()));
                pt.setGiaphong(Double.valueOf(txtGiaPhong.getText().trim()));
                pt.setDiachi(txtDiaChi.getText().trim());
                pt.setMota(txtMoTa.getText().trim());
                if (rbDaThue.isSelected()) {
                    pt.setStatus(PhongTroEnum.Rented);
                } else if (rbChuaThue.isSelected()) {
                    pt.setStatus(PhongTroEnum.Not_Yet);
                } else if (rbChoDuyet.isSelected()) {
                    pt.setStatus(PhongTroEnum.Waiting);
                }

                dao.update(pt);
                JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                LoadDataTable();
                SessionEntity ss = new SessionEntity();
                ss.setUser(userSS);
                ss.setMessage("Cập nhật phòng trọ");
                ss.setStartTime(new Timestamp(System.currentTimeMillis()));
                sessionDao.save(ss);
                SessionEntity sss = sessionDao.getLast(userSS.getId());
                setSession(sss);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        long selectedIds = getSelectedIds();
        try {
            if (JOptionPane.showConfirmDialog(null, "Xác nhận xóa?", "Xóa phòng trọ", ERROR_MESSAGE) != YES_OPTION) {
                return;
            }
         
            Dao.deleteFromRecycle(selectedIds);
            LoadDataTable();
            SessionEntity ss = new SessionEntity();
            ss.setUser(userSS);
            ss.setMessage("Xóa phòng trọ");
            ss.setStartTime(new Timestamp(System.currentTimeMillis()));
            sessionDao.save(ss);
            SessionEntity sss = sessionDao.getLast(userSS.getId());
            setSession(sss);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThungRacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThungRacActionPerformed
        // TODO add your handling code here:
        ThungRacPhongTro tr = new ThungRacPhongTro();
        tr.setVisible(true);
    }//GEN-LAST:event_btnThungRacActionPerformed

    private void btnRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestActionPerformed
        lblId.setText("");
        txtDiaChi.setText("");
        txtDienTich.setText("");
        txtGiaPhong.setText("");
        txtMaKhuVuc.setText("");
        txtMaLoaiPhong.setText("");
        txtMaNguoiDung.setText("");
        txtMoTa.setText("");
        txtTenPhong.setText("");
        txtTimKiem.setText("");
        btnGTinhTrang.clearSelection();
        LoadDataTable();
    }//GEN-LAST:event_btnRestActionPerformed

    private void tblPhongTroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhongTroMouseClicked
        // TODO add your handling code here:
        int row = tblPhongTro.getSelectedRow();
          lblId.setText(String.valueOf(tblPhongTro.getValueAt(row, 0)));
        txtMaLoaiPhong.setText(String.valueOf(tblPhongTro.getValueAt(row, 1)));
        txtMaNguoiDung.setText(String.valueOf(tblPhongTro.getValueAt(row, 2)));
        txtMaKhuVuc.setText(String.valueOf(tblPhongTro.getValueAt(row, 3)));
        txtTenPhong.setText(String.valueOf(tblPhongTro.getValueAt(row, 4)));
        txtDienTich.setText(String.valueOf(tblPhongTro.getValueAt(row, 5)));
        txtGiaPhong.setText(String.valueOf(tblPhongTro.getValueAt(row, 6)));
        txtDiaChi.setText(String.valueOf(tblPhongTro.getValueAt(row, 7)));
        txtMoTa.setText(String.valueOf(tblPhongTro.getValueAt(row, 8)));
        idPhong = lblId.getText()+"";
        idNguoiDung = txtMaNguoiDung.getText()+"";
        giaPhong=Float.parseFloat(txtGiaPhong.getText());
        if (String.valueOf(tblPhongTro.getValueAt(row, 9)).equalsIgnoreCase("Not_Yet")) {
            rbChuaThue.setSelected(true);
        } else if (String.valueOf(tblPhongTro.getValueAt(row, 9)).equalsIgnoreCase("Rented")) {
            rbDaThue.setSelected(true);
        } else if (String.valueOf(tblPhongTro.getValueAt(row, 9)).equalsIgnoreCase("Waiting")) {
            rbChoDuyet.setSelected(true);
        }
        if (rbChoDuyet.isSelected()) {
            btnTaoHopDong.setEnabled(true);
        } else {
            btnTaoHopDong.setEnabled(false);
        }
//        try {
//            long selectedID = getSelectedIds();
//            PhongTro pt = Dao.get(selectedID);
//            if (pt == null) {
//                JOptionPane.showMessageDialog(null, "Hợp đồng bạn chọn không hợp lệ");
//            }
//            txtMaLoaiPhong.setText(pt.getIdMaloaiphong()+"");
//            txtMaNguoiDung.setText(pt.getIdNguoidung()+"");
//            txtMaKhuVuc.setText(pt.getIdKhuvuc()+"");
//            txtTenPhong.setText(pt.getTenphong());
//            txtDienTich.setText(pt.getDientich()+"");
//            txtGiaPhong.setText(pt.getGiaphong()+"");
//            txtDiaChi.setText(pt.getDiachi());
//            txtMoTa.setText(pt.getMota());
//            System.out.println(pt.getStatus());
//            if (pt.getStatus().equals("Not_Yet")) {
//                rbChuaThue.setSelected(true);
//            } else if (pt.getStatus().equals("Rented")) {
//                rbDaThue.setSelected(true);
//            } else if (pt.getStatus().equals("Waiting")) {
//                rbChoDuyet.setSelected(true);
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(PhongTroPanel.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
    }//GEN-LAST:event_tblPhongTroMouseClicked

    private void txtTimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusGained
        // TODO add your handling code here:
        if (txtTimKiem.getText().equals("Nhập mã phòng trọ để tìm kiếm phòng!")) {
            txtTimKiem.setText("");
        }
    }//GEN-LAST:event_txtTimKiemFocusGained

    private void txtTimKiemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusLost
        // TODO add your handling code here:
        if (txtTimKiem.getText().isEmpty()) {
            txtTimKiem.setText("Nhập mã phòng trọ để tìm kiếm phòng!");
        }
    }//GEN-LAST:event_txtTimKiemFocusLost

    private void btnTaoHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoHopDongActionPerformed
        try {
            ThemHopDong them = new ThemHopDong();
            them.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(PhongTroPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTaoHopDongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGTinhTrang;
    private javax.swing.JButton btnRest;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTaoHopDong;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThungRac;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblId;
    private javax.swing.JRadioButton rbChoDuyet;
    private javax.swing.JRadioButton rbChuaThue;
    private javax.swing.JRadioButton rbDaThue;
    private javax.swing.JComboBox<String> statusComboBox1;
    private javax.swing.JTable tblPhongTro;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDienTich;
    private javax.swing.JTextField txtGiaPhong;
    private javax.swing.JTextField txtMaKhuVuc;
    private javax.swing.JTextField txtMaLoaiPhong;
    private javax.swing.JTextField txtMaNguoiDung;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtTenPhong;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
