/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TroViet.Views.Login;

import static TroViet.Connect.SQL_Connection.con;
import TroViet.DAO.DanhGiaDAO;
import TroViet.DAO.PhongTroDAO;
import TroViet.Model.DanhGia;
import TroViet.Model.PhongTro;
import TroViet.Utils.SessionManager;
import TroViet.Utils.ShutdownHook;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WINDOWS
 */
public class TrangChuChung extends javax.swing.JFrame {

    /**
     * Creates new form TrangChuChung
     */
    
    DefaultTableModel tblModel;
    PhongTroDAO ptDAO = new PhongTroDAO();
    DanhGiaDAO dgDAO = new DanhGiaDAO();
    
    public TrangChuChung() throws SQLException {
        initComponents();
//        ManHinhChao chao = new ManHinhChao(this, true);
//        chao.setVisible(true);
        setLocationRelativeTo(null);
        initTable();
        fillToPhongTrong();
    }
    
    public void initTable() {
        tblModel = (DefaultTableModel) tblPhongTrong.getModel();
        String[] columns = {"Tên phòng", "Diện tích", "Giá phòng", "Địa chỉ", "Mô tả", "Đánh giá", "Nội dung"};
        tblModel.setColumnIdentifiers(columns);
    }
    
    public void fillToPhongTrong() throws SQLException {
        tblModel.setRowCount(0);
        String query = "select pt.TenPhong, pt.DienTich, pt.GiaPhong, pt.DiaChi, pt.MoTa, dg.DanhGia, dg.NoiDung\n" +
                            "from PhongTro pt join DanhGia dg on pt.Id = dg.IdMaPhongTro\n" +
                            "where pt.Status=0;";
        PreparedStatement ps = con.prepareStatement(query);
        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            Vector<Object> vec = new Vector<Object>();
            vec.add(rs.getString(1));
            vec.add(rs.getString(2));
            vec.add(rs.getString(3));
            vec.add(rs.getString(4));
            vec.add(rs.getString(5));
//            vec.add(rs.getString(6));
//            vec.add(rs.getString(7));
//            tblModel.addRow(vec);
 int danhGia = Integer.parseInt(rs.getString(6));
        String stars = "*".repeat(danhGia);
        vec.add(stars);
        vec.add(rs.getString(7));
        tblModel.addRow(vec);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhongTrong = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnTangDan = new javax.swing.JButton();
        btnGiamDan = new javax.swing.JButton();
        btnDanhGia = new javax.swing.JButton();
        lblDangKy = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTrangChu = new javax.swing.JMenu();
        jMenuNguoiDung = new javax.swing.JMenu();
        DangNhap = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        DangKy = new javax.swing.JMenu();
        jMenuThoat = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(40, 46, 62));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 630));

        tblPhongTrong.setBackground(new java.awt.Color(207, 243, 243));
        tblPhongTrong.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblPhongTrong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPhongTrong.setGridColor(new java.awt.Color(255, 255, 255));
        tblPhongTrong.setSelectionBackground(new java.awt.Color(40, 46, 62));
        tblPhongTrong.setSelectionForeground(new java.awt.Color(255, 205, 31));
        tblPhongTrong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhongTrongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhongTrong);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 205, 31));
        jLabel2.setText("DANH SÁCH PHÒNG TRỐNG");

        btnTangDan.setBackground(new java.awt.Color(255, 205, 31));
        btnTangDan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTangDan.setForeground(new java.awt.Color(40, 46, 62));
        btnTangDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/up-arrow.png"))); // NOI18N
        btnTangDan.setText("Giá tăng dần");
        btnTangDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTangDanActionPerformed(evt);
            }
        });

        btnGiamDan.setBackground(new java.awt.Color(255, 205, 31));
        btnGiamDan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGiamDan.setForeground(new java.awt.Color(40, 46, 62));
        btnGiamDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/down-arrow.png"))); // NOI18N
        btnGiamDan.setText("Giá giảm dần");
        btnGiamDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiamDanActionPerformed(evt);
            }
        });

        btnDanhGia.setBackground(new java.awt.Color(255, 205, 31));
        btnDanhGia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDanhGia.setForeground(new java.awt.Color(40, 46, 62));
        btnDanhGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/line-chart.png"))); // NOI18N
        btnDanhGia.setText("Sắp xếp theo đánh giá");
        btnDanhGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhGiaActionPerformed(evt);
            }
        });

        lblDangKy.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDangKy.setForeground(new java.awt.Color(255, 205, 31));
        lblDangKy.setText("ĐĂNG KÝ");
        lblDangKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangKyMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NGAY ĐỂ ĐẶT PHÒNG!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jLabel2)))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDangKy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTangDan, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGiamDan, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnDanhGia)
                .addGap(127, 127, 127))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGiamDan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDanhGia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTangDan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDangKy)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26))
        );

        jMenuBar1.setBackground(new java.awt.Color(46, 56, 86));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 205, 31), 2));
        jMenuBar1.setForeground(new java.awt.Color(40, 46, 62));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(615, 70));

        jMenuTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        jMenuTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/home (1).png"))); // NOI18N
        jMenuTrangChu.setText("Trang chủ");
        jMenuTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuBar1.add(jMenuTrangChu);

        jMenuNguoiDung.setForeground(new java.awt.Color(255, 255, 255));
        jMenuNguoiDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/user.png"))); // NOI18N
        jMenuNguoiDung.setText("Người dùng");
        jMenuNguoiDung.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        DangNhap.setForeground(new java.awt.Color(40, 46, 62));
        DangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/user (1).png"))); // NOI18N
        DangNhap.setText("Đăng nhập");
        DangNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DangNhapMouseClicked(evt);
            }
        });
        jMenuNguoiDung.add(DangNhap);
        jMenuNguoiDung.add(jSeparator5);

        DangKy.setForeground(new java.awt.Color(40, 46, 62));
        DangKy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/edit.png"))); // NOI18N
        DangKy.setText("Đăng ký");
        DangKy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DangKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DangKyMouseClicked(evt);
            }
        });
        jMenuNguoiDung.add(DangKy);

        jMenuBar1.add(jMenuNguoiDung);

        jMenuThoat.setForeground(new java.awt.Color(255, 255, 255));
        jMenuThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TroViet/Icon/logout.png"))); // NOI18N
        jMenuThoat.setText("Thoát");
        jMenuThoat.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuThoatMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuThoat);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangNhapMouseClicked
        // TODO add your handling code here:
        this.dispose();
        DangNhap dangnhap = new DangNhap();
        dangnhap.setVisible(true);
    }//GEN-LAST:event_DangNhapMouseClicked

    private void DangKyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DangKyMouseClicked
        // TODO add your handling code here:
        this.dispose();
        DangKy dangky = new DangKy();
        dangky.setVisible(true);
    }//GEN-LAST:event_DangKyMouseClicked

    private void jMenuThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuThoatMouseClicked
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(rootPane, "Bạn muốn đóng ứng dụng?", "Thoát?", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            try {
                System.exit(0);
                SessionManager.update();// Đẵng xuất
            } catch (SQLException ex) {
                Logger.getLogger(TrangChuChung.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuThoatMouseClicked

    private void btnTangDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTangDanActionPerformed
        // TODO add your handling code here:
        try {
            tblModel.setRowCount(0);
            String query = "select pt.TenPhong, pt.DienTich, pt.GiaPhong, pt.DiaChi, pt.MoTa, dg.DanhGia, dg.NoiDung\n"
                    + "from PhongTro pt join DanhGia dg on pt.Id = dg.IdMaPhongTro\n"
                    + "where pt.Status=0 order by pt.GiaPhong asc;";
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector<Object> vec = new Vector<Object>();
                vec.add(rs.getString(1));
                vec.add(rs.getString(2));
                vec.add(rs.getString(3));
                vec.add(rs.getString(4));
                vec.add(rs.getString(5));
//                vec.add(rs.getString(6));
//                vec.add(rs.getString(7));
//                tblModel.addRow(vec);
 int danhGia = Integer.parseInt(rs.getString(6));
        String stars = "*".repeat(danhGia);
        vec.add(stars);
        vec.add(rs.getString(7));
        tblModel.addRow(vec);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TrangChuChung.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTangDanActionPerformed

    private void btnGiamDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiamDanActionPerformed
        // TODO add your handling code here:
        try {
            tblModel.setRowCount(0);
            String query = "select pt.TenPhong, pt.DienTich, pt.GiaPhong, pt.DiaChi, pt.MoTa, dg.DanhGia, dg.NoiDung\n"
                    + "from PhongTro pt join DanhGia dg on pt.Id = dg.IdMaPhongTro\n"
                    + "where pt.Status=0 order by pt.GiaPhong desc;";
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector<Object> vec = new Vector<Object>();
                vec.add(rs.getString(1));
                vec.add(rs.getString(2));
                vec.add(rs.getString(3));
                vec.add(rs.getString(4));
                vec.add(rs.getString(5));
//                vec.add(rs.getString(6));
//                vec.add(rs.getString(7));
//                tblModel.addRow(vec);
 int danhGia = Integer.parseInt(rs.getString(6));
        String stars = "*".repeat(danhGia);
        vec.add(stars);
        vec.add(rs.getString(7));
        tblModel.addRow(vec);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TrangChuChung.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGiamDanActionPerformed

    private void btnDanhGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhGiaActionPerformed
        // TODO add your handling code here:
        try {
            tblModel.setRowCount(0);
            String query = "select pt.TenPhong, pt.DienTich, pt.GiaPhong, pt.DiaChi, pt.MoTa, dg.DanhGia, dg.NoiDung\n"
                    + "from PhongTro pt join DanhGia dg on pt.Id = dg.IdMaPhongTro\n"
                    + "where pt.Status=0 order by dg.DanhGia desc;";
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector<Object> vec = new Vector<Object>();
                vec.add(rs.getString(1));
                vec.add(rs.getString(2));
                vec.add(rs.getString(3));
                vec.add(rs.getString(4));
                vec.add(rs.getString(5));
//                vec.add(rs.getString(6));
//                vec.add(rs.getString(7));
//                tblModel.addRow(vec);
 int danhGia = Integer.parseInt(rs.getString(6));
        String stars = "*".repeat(danhGia);
        vec.add(stars);
        vec.add(rs.getString(7));
        tblModel.addRow(vec);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TrangChuChung.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDanhGiaActionPerformed

    private void lblDangKyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangKyMouseClicked
        // TODO add your handling code here:
        this.dispose();
        DangKy dangky = new DangKy();
        dangky.setVisible(true);
    }//GEN-LAST:event_lblDangKyMouseClicked

    private void tblPhongTrongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhongTrongMouseClicked
        // TODO add your handling code here:
        HinhAnh hinh = new HinhAnh();
        hinh.setVisible(true);
    }//GEN-LAST:event_tblPhongTrongMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
        } catch (InstantiationException ex) {
        } catch (IllegalAccessException ex) {
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        }
        
        
         Runtime.getRuntime().addShutdownHook(new ShutdownHook());
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TrangChuChung().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TrangChuChung.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu DangKy;
    private javax.swing.JMenu DangNhap;
    private javax.swing.JButton btnDanhGia;
    private javax.swing.JButton btnGiamDan;
    private javax.swing.JButton btnTangDan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuNguoiDung;
    private javax.swing.JMenu jMenuThoat;
    private javax.swing.JMenu jMenuTrangChu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JLabel lblDangKy;
    private javax.swing.JTable tblPhongTrong;
    // End of variables declaration//GEN-END:variables
}
